# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  test_js:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: echo "$GITHUB_REPOSITORY_OWNER"
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm run build --if-present 
    - run: npm test
    
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #- name: docker login
    #  env:
    #    DDOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    #    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #  run: |
    #   docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nodetest
      #run: docker build . --file Dockerfile --tag testv1/node-test:$(date +%s)
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
          #images: my-docker-hub-namespace/my-docker-hub-repository  
           images: shaynesxm/shaynesxm
           
    - name: login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: nodejs-perso
          tags: shaynesxm/test-ci/nodejs:1
          #tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
   # - name: Docker push
      #run: docker push ${{secrets.DOCKER_USERNAME}}/shaynesxm
      #run: docker push nodetest
    #  run: docker push ${{secrets.DOCKER_USERNAME}}/shaynesxm
      #run: docker push testv1/node-test:$(date +%s)
